### ISSUE TITLE
Rebuild of a solution targeting multiple frameworks fails on Visual Studio 17.2.0 & 17.2.1

### ISSUE THREAD

**Issue by MWiso** [manuelroemer/IsExternalInit#13]
It might be Microsoft's fault but on Visual Studio 17.2.0 & 17.2.1 a build of a solution targeting multiple frameworks and containing your package works fine, whereas a rebuild always fails with "Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported".

It can easily be reproduced with your test project **PackageReference.MultiTarget**.
Clean & Build works fine.
Rebuild fails.

**Comment by manuelroemer** [comment]
Hey, the issue also appears in the `Nullable` package. We have another issue [here](https://github.com/manuelroemer/Nullable/issues/24) which has a little more discussion. At the moment it seems that there is a regression in the tooling and an issue has already been opened in the .NET SDK repository. Unless anybody else has an idea as to what might be wrong, we will have to wait what comes out of that. Any additional information (either here or on the issue linked in my comment) is much appreciated!

**Comment by gtbuchanan** [comment]
This might be fixed by #14.

**Comment by manuelroemer** [comment]
I just merged #14 by @gtbuchanan and published the new package version 1.0.3 on NuGet. During my local tests the issue indeed seemed to be fixed (using .NET SDK 6.0.300). I will preemptively close this issue, but if someone still has any problems in this area even with the newer version, feel free to message me or simply reopen this issue.
Many thanks to all people involved (so far 😉)!
